// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Dencyuman/logvista-server/src/database"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func initializeDB() (*gorm.DB, error) {
	db, err := database.Connect()
	if err != nil {
		return nil, err
	}
	return db, nil
}
