// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "200 OKが返ってくれば起動済み",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "general"
                ],
                "summary": "Logvistaヘルスチェック用エンドポイント",
                "responses": {
                    "200": {
                        "description": "Logvista API Server is running!",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/healthcheck/configs": {
            "post": {
                "description": "200 ヘルスチェックを設定する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "ヘルスチェック設定用エンドポイント",
                "parameters": [
                    {
                        "description": "ヘルスチェック用設定値",
                        "name": "config",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/schemas.HealthcheckConfigBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.HealthcheckConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthcheck/configs/": {
            "get": {
                "description": "200 システム別ヘルスチェック設定一覧の取得",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "ヘルスチェック設定取得用エンドポイント",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.HealthcheckConfigsResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthcheck/configs/systems/{systemId}": {
            "get": {
                "description": "200 systemIdで指定したシステムに紐づくヘルスチェック設定一覧の取得",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "ヘルスチェック設定取得用エンドポイント(システム別)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "システムid",
                        "name": "systemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.HealthcheckConfigsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthcheck/configs/test": {
            "post": {
                "description": "200 設定通りにヘルスチェックを１回実行した結果を取得できる",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "ヘルスチェック設定テスト用エンドポイント",
                "parameters": [
                    {
                        "description": "ヘルスチェック用設定値",
                        "name": "config",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/schemas.TestHealthcheckConfigBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.TestHealthcheckConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthcheck/configs/{configId}": {
            "put": {
                "description": "ヘルスチェックの設定を更新する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "ヘルスチェックConfig更新用エンドポイント",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configのid",
                        "name": "configId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ヘルスチェック設定",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.HealthcheckConfigBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "ヘルスチェックの設定を削除する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "ヘルスチェックConfig削除用エンドポイント",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configのid",
                        "name": "configId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthcheck/configs/{configId}/logs": {
            "get": {
                "description": "200 ヘルスチェックログ一覧の取得",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "ヘルスチェックログ取得用エンドポイント",
                "parameters": [
                    {
                        "type": "string",
                        "description": "設定ID",
                        "name": "configId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "取得ログデータ件数",
                        "name": "count",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "降順フラグ",
                        "name": "desc",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.HealthcheckLogsListResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logs/": {
            "get": {
                "description": "蓄積されているログ情報を取得する。クエリパラメータでフィルタリングが可能。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "取得ログ情報",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "現在のページ",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "1ページあたりのアイテム数",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "検索する日付の開始範囲 (形式: YYYY-MM-DDTHH:MM:SSZ)",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "検索する日付の終了範囲 (形式: YYYY-MM-DDTHH:MM:SSZ)",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ログレベルでのフィルタ",
                        "name": "levelName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "システムidでのフィルタ",
                        "name": "systemId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "メッセージ内容の部分一致フィルタ",
                        "name": "containMsg",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "エラーの種類でのフィルタ",
                        "name": "excType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "エラーの詳細でのキーワード部分一致フィルタ",
                        "name": "excDetail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ファイル名でのフィルタ",
                        "name": "fileName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "エラーが発生した行番号でのフィルタ",
                        "name": "lineno",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.PaginatedLogResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logs/python-logvista": {
            "post": {
                "description": "json形式の配列で受け取ったログ情報を記録する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "python-logvista用エンドポイント",
                "parameters": [
                    {
                        "description": "ログデータ",
                        "name": "logs",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.Log"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.Log"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/masters/error-types": {
            "get": {
                "description": "DB上に存在するエラー型名一覧を取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "masters"
                ],
                "summary": "エラー型名一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/masters/files": {
            "get": {
                "description": "DB上に存在するファイル名一覧を取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "masters"
                ],
                "summary": "ファイル名一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/masters/levels": {
            "get": {
                "description": "DB上に存在するログレベル一覧を取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "masters"
                ],
                "summary": "ログレベル一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/systems/": {
            "get": {
                "description": "DB上に存在するシステム一覧を取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systems"
                ],
                "summary": "システム一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.SystemResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/systems/summary": {
            "get": {
                "description": "DB上に存在するシステム別集計情報を取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systems"
                ],
                "summary": "システム集計情報取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "システムid：指定しない場合は全てのシステムを取得",
                        "name": "systemId",
                        "in": "query"
                    },
                    {
                        "minimum": 10,
                        "type": "integer",
                        "default": 3600,
                        "description": "集計時間スパン（秒）: 10秒刻みで指定可能",
                        "name": "timeSpan",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 12,
                        "description": "取得データ個数",
                        "name": "dataCount",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.Summary"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/systems/{systemId}": {
            "put": {
                "description": "DB上に存在するシステムを更新する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systems"
                ],
                "summary": "システム更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "システムid",
                        "name": "systemId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update System Request",
                        "name": "system",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.SystemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "システムとその関連ログデータを削除する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systems"
                ],
                "summary": "システム削除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "システムid",
                        "name": "systemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.HealthcheckConfigType": {
            "type": "string",
            "enum": [
                "SiteTitle",
                "Endpoint"
            ],
            "x-enum-varnames": [
                "SiteTitle",
                "Endpoint"
            ]
        },
        "schemas.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "schemas.HealthcheckConfigBody": {
            "type": "object",
            "required": [
                "config_type",
                "system_id"
            ],
            "properties": {
                "config_type": {
                    "description": "設定タイプ",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.HealthcheckConfigType"
                        }
                    ],
                    "example": "SiteTitle"
                },
                "description": {
                    "description": "設定の説明",
                    "type": "string",
                    "example": "sampleDescription"
                },
                "expected_value": {
                    "description": "想定値",
                    "type": "string",
                    "example": "sampleValue"
                },
                "is_active": {
                    "description": "有効かどうか",
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "description": "設定名",
                    "type": "string",
                    "example": "sampleName"
                },
                "system_id": {
                    "description": "システムid",
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "url": {
                    "description": "アクセス先url",
                    "type": "string",
                    "example": "http://localhost:8080/"
                }
            }
        },
        "schemas.HealthcheckConfigResponse": {
            "type": "object",
            "required": [
                "config_type"
            ],
            "properties": {
                "config_type": {
                    "description": "設定タイプ",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.HealthcheckConfigType"
                        }
                    ],
                    "example": "SiteTitle"
                },
                "created_at": {
                    "description": "作成日時",
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                },
                "description": {
                    "description": "設定の説明",
                    "type": "string",
                    "example": "sampleDescription"
                },
                "expected_value": {
                    "description": "想定値",
                    "type": "string",
                    "example": "sampleValue"
                },
                "id": {
                    "description": "設定ID",
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "is_active": {
                    "description": "有効かどうか",
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "description": "設定名",
                    "type": "string",
                    "example": "sampleName"
                },
                "system_id": {
                    "description": "システムID",
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "updated_at": {
                    "description": "更新日時",
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                },
                "url": {
                    "description": "アクセス先url",
                    "type": "string",
                    "example": "http://localhost:8080/"
                }
            }
        },
        "schemas.HealthcheckConfigsResponse": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "updated_at"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "example": "API Server"
                },
                "configs": {
                    "description": "Config",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.HealthcheckConfigResponse"
                    }
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                },
                "id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "name": {
                    "type": "string",
                    "example": "sample_system"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                }
            }
        },
        "schemas.HealthcheckLogsListResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "ヘルスチェック設定",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schemas.HealthcheckConfigResponse"
                        }
                    ]
                },
                "logs": {
                    "description": "ログリスト",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.HealthcheckLogsResponse"
                    }
                }
            }
        },
        "schemas.HealthcheckLogsResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "作成日時",
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                },
                "healthcheck_config_id": {
                    "description": "ヘルスチェック設定ID",
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "id": {
                    "description": "ログID",
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "is_alive": {
                    "description": "ヘルスチェック結果",
                    "type": "boolean",
                    "example": true
                },
                "response_value": {
                    "description": "レスポンス値",
                    "type": "string",
                    "example": "sampleResponse"
                },
                "updated_at": {
                    "description": "更新日時",
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                }
            }
        },
        "schemas.Log": {
            "type": "object",
            "required": [
                "id",
                "level_name",
                "timestamp"
            ],
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "available_memory": {
                    "type": "integer",
                    "example": 8000000
                },
                "cpu_idle_time": {
                    "type": "number",
                    "example": 10000
                },
                "cpu_percent": {
                    "type": "number",
                    "example": 0
                },
                "cpu_system_time": {
                    "type": "number",
                    "example": 500
                },
                "cpu_user_time": {
                    "type": "number",
                    "example": 700
                },
                "exc_detail": {
                    "type": "string",
                    "example": "Some traceback details here"
                },
                "exc_traceback": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.Traceback"
                    }
                },
                "exc_type": {
                    "type": "string",
                    "example": "Exception"
                },
                "exc_value": {
                    "type": "string",
                    "example": "sample"
                },
                "file_name": {
                    "type": "string",
                    "example": "sample.py"
                },
                "free_memory": {
                    "type": "integer",
                    "example": 8000000
                },
                "func_name": {
                    "type": "string",
                    "example": "\u003cmodule\u003e"
                },
                "id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "level_name": {
                    "type": "string",
                    "example": "INFO"
                },
                "levelno": {
                    "type": "integer",
                    "example": 20
                },
                "lineno": {
                    "type": "integer",
                    "example": 1
                },
                "memory_percent": {
                    "type": "number",
                    "example": 50
                },
                "message": {
                    "type": "string",
                    "example": "sample message"
                },
                "module": {
                    "type": "string",
                    "example": "sample"
                },
                "name": {
                    "type": "string",
                    "example": "sample"
                },
                "process": {
                    "type": "integer",
                    "example": 1000
                },
                "process_name": {
                    "type": "string",
                    "example": "MainProcess"
                },
                "system_name": {
                    "type": "string",
                    "example": "sample_system"
                },
                "thread": {
                    "type": "integer",
                    "example": 10000
                },
                "thread_name": {
                    "type": "string",
                    "example": "MainThread"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                },
                "total_memory": {
                    "type": "integer",
                    "example": 16000000
                },
                "used_memory": {
                    "type": "integer",
                    "example": 8000000
                }
            }
        },
        "schemas.LogResponse": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "level_name",
                "system",
                "timestamp",
                "updated_at"
            ],
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "available_memory": {
                    "type": "integer",
                    "example": 8000000
                },
                "cpu_idle_time": {
                    "type": "number",
                    "example": 10000
                },
                "cpu_percent": {
                    "type": "number",
                    "example": 0
                },
                "cpu_system_time": {
                    "type": "number",
                    "example": 500
                },
                "cpu_user_time": {
                    "type": "number",
                    "example": 700
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                },
                "exc_detail": {
                    "type": "string",
                    "example": "Some traceback details here"
                },
                "exc_traceback": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.TracebackResponse"
                    }
                },
                "exc_type": {
                    "type": "string",
                    "example": "Exception"
                },
                "exc_value": {
                    "type": "string",
                    "example": "sample"
                },
                "file_name": {
                    "type": "string",
                    "example": "sample.py"
                },
                "free_memory": {
                    "type": "integer",
                    "example": 8000000
                },
                "func_name": {
                    "type": "string",
                    "example": "\u003cmodule\u003e"
                },
                "id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "level_name": {
                    "type": "string",
                    "example": "INFO"
                },
                "levelno": {
                    "type": "integer",
                    "example": 20
                },
                "lineno": {
                    "type": "integer",
                    "example": 1
                },
                "memory_percent": {
                    "type": "number",
                    "example": 50
                },
                "message": {
                    "type": "string",
                    "example": "sample message"
                },
                "module": {
                    "type": "string",
                    "example": "sample"
                },
                "name": {
                    "type": "string",
                    "example": "sample"
                },
                "process": {
                    "type": "integer",
                    "example": 1000
                },
                "process_name": {
                    "type": "string",
                    "example": "MainProcess"
                },
                "system": {
                    "$ref": "#/definitions/schemas.SystemResponse"
                },
                "system_name": {
                    "type": "string",
                    "example": "sample_system"
                },
                "thread": {
                    "type": "integer",
                    "example": 10000
                },
                "thread_name": {
                    "type": "string",
                    "example": "MainThread"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                },
                "total_memory": {
                    "type": "integer",
                    "example": 16000000
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                },
                "used_memory": {
                    "type": "integer",
                    "example": 8000000
                }
            }
        },
        "schemas.PaginatedLogResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "ログの配列",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.LogResponse"
                    }
                },
                "limit": {
                    "description": "1ページあたりのアイテム数",
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "description": "現在のページ数",
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "description": "総アイテム数",
                    "type": "integer",
                    "example": 100
                },
                "total_pages": {
                    "description": "総ページ数",
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "schemas.ResponseMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "schemas.Summary": {
            "type": "object",
            "required": [
                "created_at",
                "data",
                "id",
                "latest_log",
                "updated_at"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "example": "API Server"
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.SummaryData"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "latest_log": {
                    "$ref": "#/definitions/schemas.LogResponse"
                },
                "name": {
                    "type": "string",
                    "example": "sample_system"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                }
            }
        },
        "schemas.SummaryData": {
            "type": "object",
            "required": [
                "base_time",
                "errorlog_count",
                "infolog_count",
                "warninglog_count"
            ],
            "properties": {
                "base_time": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                },
                "errorlog_count": {
                    "type": "integer",
                    "example": 10
                },
                "infolog_count": {
                    "type": "integer",
                    "example": 10
                },
                "warninglog_count": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "schemas.SystemRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "API Server"
                }
            }
        },
        "schemas.SystemResponse": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "updated_at"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "example": "API Server"
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                },
                "id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "name": {
                    "type": "string",
                    "example": "sample_system"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00.000000+09:00"
                }
            }
        },
        "schemas.TestHealthcheckConfigBody": {
            "type": "object",
            "required": [
                "config_type"
            ],
            "properties": {
                "config_type": {
                    "description": "設定タイプ",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.HealthcheckConfigType"
                        }
                    ],
                    "example": "SiteTitle"
                },
                "expected_value": {
                    "description": "想定値",
                    "type": "string",
                    "example": "sampleValue"
                },
                "url": {
                    "description": "アクセス先url",
                    "type": "string",
                    "example": "http://localhost:8080/"
                }
            }
        },
        "schemas.TestHealthcheckConfigResponse": {
            "type": "object",
            "required": [
                "config_type"
            ],
            "properties": {
                "config_type": {
                    "description": "設定タイプ",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.HealthcheckConfigType"
                        }
                    ],
                    "example": "SiteTitle"
                },
                "expected_value": {
                    "description": "想定値",
                    "type": "string",
                    "example": "sampleValue"
                },
                "fetched-value": {
                    "description": "取得された値",
                    "type": "string",
                    "example": "sampleValue"
                },
                "healthcheck_result": {
                    "description": "ヘルスチェック結果",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "schemas.Traceback": {
            "type": "object",
            "properties": {
                "tb_filename": {
                    "type": "string",
                    "example": "C:\\User\\USER\\sample.py"
                },
                "tb_line": {
                    "type": "string",
                    "example": "raise Exception(\"sample\")"
                },
                "tb_lineno": {
                    "type": "integer",
                    "example": 31
                },
                "tb_name": {
                    "type": "string",
                    "example": "\u003cmodule\u003e"
                }
            }
        },
        "schemas.TracebackResponse": {
            "type": "object",
            "properties": {
                "tb_filename": {
                    "type": "string",
                    "example": "C:\\User\\USER\\sample.py"
                },
                "tb_line": {
                    "type": "string",
                    "example": "raise Exception(\"sample\")"
                },
                "tb_lineno": {
                    "type": "integer",
                    "example": 31
                },
                "tb_name": {
                    "type": "string",
                    "example": "\u003cmodule\u003e"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.13",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Logvista API",
	Description:      "This is Logvista server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
