basePath: /api/v1
definitions:
  schemas.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  schemas.Log:
    properties:
      attributes:
        additionalProperties: true
        type: object
      available_memory:
        example: 8000000
        type: integer
      cpu_idle_time:
        example: 10000
        type: number
      cpu_percent:
        example: 0
        type: number
      cpu_system_time:
        example: 500
        type: number
      cpu_user_time:
        example: 700
        type: number
      exc_detail:
        example: Some traceback details here
        type: string
      exc_traceback:
        items:
          $ref: '#/definitions/schemas.Traceback'
        type: array
      exc_type:
        example: Exception
        type: string
      exc_value:
        example: sample
        type: string
      file_name:
        example: sample.py
        type: string
      free_memory:
        example: 8000000
        type: integer
      func_name:
        example: <module>
        type: string
      id:
        example: 00000000-0000-0000-0000-000000000000
        type: string
      level_name:
        example: INFO
        type: string
      levelno:
        example: 20
        type: integer
      lineno:
        example: 1
        type: integer
      memory_percent:
        example: 50
        type: number
      message:
        example: sample message
        type: string
      module:
        example: sample
        type: string
      name:
        example: sample
        type: string
      process:
        example: 1000
        type: integer
      process_name:
        example: MainProcess
        type: string
      system_name:
        example: sample_system
        type: string
      thread:
        example: 10000
        type: integer
      thread_name:
        example: MainThread
        type: string
      timestamp:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
      total_memory:
        example: 16000000
        type: integer
      used_memory:
        example: 8000000
        type: integer
    required:
    - id
    - level_name
    - timestamp
    type: object
  schemas.LogResponse:
    properties:
      attributes:
        additionalProperties: true
        type: object
      available_memory:
        example: 8000000
        type: integer
      cpu_idle_time:
        example: 10000
        type: number
      cpu_percent:
        example: 0
        type: number
      cpu_system_time:
        example: 500
        type: number
      cpu_user_time:
        example: 700
        type: number
      created_at:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
      exc_detail:
        example: Some traceback details here
        type: string
      exc_traceback:
        items:
          $ref: '#/definitions/schemas.TracebackResponse'
        type: array
      exc_type:
        example: Exception
        type: string
      exc_value:
        example: sample
        type: string
      file_name:
        example: sample.py
        type: string
      free_memory:
        example: 8000000
        type: integer
      func_name:
        example: <module>
        type: string
      id:
        example: 00000000-0000-0000-0000-000000000000
        type: string
      level_name:
        example: INFO
        type: string
      levelno:
        example: 20
        type: integer
      lineno:
        example: 1
        type: integer
      memory_percent:
        example: 50
        type: number
      message:
        example: sample message
        type: string
      module:
        example: sample
        type: string
      name:
        example: sample
        type: string
      process:
        example: 1000
        type: integer
      process_name:
        example: MainProcess
        type: string
      system_name:
        example: sample_system
        type: string
      thread:
        example: 10000
        type: integer
      thread_name:
        example: MainThread
        type: string
      timestamp:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
      total_memory:
        example: 16000000
        type: integer
      updated_at:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
      used_memory:
        example: 8000000
        type: integer
    required:
    - created_at
    - id
    - level_name
    - timestamp
    - updated_at
    type: object
  schemas.ResponseMessage:
    properties:
      message:
        type: string
    type: object
  schemas.Traceback:
    properties:
      tb_filename:
        example: C:\User\USER\sample.py
        type: string
      tb_line:
        example: raise Exception("sample")
        type: string
      tb_lineno:
        example: 31
        type: integer
      tb_name:
        example: <module>
        type: string
    type: object
  schemas.TracebackResponse:
    properties:
      created_at:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
      tb_filename:
        example: C:\User\USER\sample.py
        type: string
      tb_line:
        example: raise Exception("sample")
        type: string
      tb_lineno:
        example: 31
        type: integer
      tb_name:
        example: <module>
        type: string
      updated_at:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
    required:
    - created_at
    - updated_at
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: This is LogVista server.
  title: LogVista API
  version: 0.0.1
paths:
  /healthcheck:
    get:
      consumes:
      - application/json
      description: 200 OKが返ってくれば起動済み
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: ヘルスチェック用エンドポイント
      tags:
      - general
  /logs/:
    get:
      consumes:
      - application/json
      description: 蓄積されているログ情報の一覧を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.LogResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: log情報取得用エンドポイント
      tags:
      - logs
  /logs/python-logvista:
    post:
      consumes:
      - application/json
      description: json形式の配列で受け取ったログ情報を記録する
      parameters:
      - description: ログデータ
        in: body
        name: logs
        schema:
          items:
            $ref: '#/definitions/schemas.Log'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.LogResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: python-logvista用エンドポイント
      tags:
      - logs
swagger: "2.0"
