basePath: /api/v1
definitions:
  schemas.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  schemas.Log:
    properties:
      attributes:
        additionalProperties: true
        type: object
      available_memory:
        example: 8000000
        type: integer
      cpu_idle_time:
        example: 10000
        type: number
      cpu_percent:
        example: 0
        type: number
      cpu_system_time:
        example: 500
        type: number
      cpu_user_time:
        example: 700
        type: number
      exc_detail:
        example: Some traceback details here
        type: string
      exc_traceback:
        items:
          $ref: '#/definitions/schemas.Traceback'
        type: array
      exc_type:
        example: Exception
        type: string
      exc_value:
        example: sample
        type: string
      file_name:
        example: sample.py
        type: string
      free_memory:
        example: 8000000
        type: integer
      func_name:
        example: <module>
        type: string
      id:
        example: 00000000-0000-0000-0000-000000000000
        type: string
      level_name:
        example: INFO
        type: string
      levelno:
        example: 20
        type: integer
      lineno:
        example: 1
        type: integer
      memory_percent:
        example: 50
        type: number
      message:
        example: sample message
        type: string
      module:
        example: sample
        type: string
      name:
        example: sample
        type: string
      process:
        example: 1000
        type: integer
      process_name:
        example: MainProcess
        type: string
      system:
        $ref: '#/definitions/schemas.SystemResponse'
      thread:
        example: 10000
        type: integer
      thread_name:
        example: MainThread
        type: string
      timestamp:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
      total_memory:
        example: 16000000
        type: integer
      used_memory:
        example: 8000000
        type: integer
    required:
    - id
    - level_name
    - system
    - timestamp
    type: object
  schemas.LogResponse:
    properties:
      attributes:
        additionalProperties: true
        type: object
      available_memory:
        example: 8000000
        type: integer
      cpu_idle_time:
        example: 10000
        type: number
      cpu_percent:
        example: 0
        type: number
      cpu_system_time:
        example: 500
        type: number
      cpu_user_time:
        example: 700
        type: number
      created_at:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
      exc_detail:
        example: Some traceback details here
        type: string
      exc_traceback:
        items:
          $ref: '#/definitions/schemas.TracebackResponse'
        type: array
      exc_type:
        example: Exception
        type: string
      exc_value:
        example: sample
        type: string
      file_name:
        example: sample.py
        type: string
      free_memory:
        example: 8000000
        type: integer
      func_name:
        example: <module>
        type: string
      id:
        example: 00000000-0000-0000-0000-000000000000
        type: string
      level_name:
        example: INFO
        type: string
      levelno:
        example: 20
        type: integer
      lineno:
        example: 1
        type: integer
      memory_percent:
        example: 50
        type: number
      message:
        example: sample message
        type: string
      module:
        example: sample
        type: string
      name:
        example: sample
        type: string
      process:
        example: 1000
        type: integer
      process_name:
        example: MainProcess
        type: string
      system:
        $ref: '#/definitions/schemas.SystemResponse'
      thread:
        example: 10000
        type: integer
      thread_name:
        example: MainThread
        type: string
      timestamp:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
      total_memory:
        example: 16000000
        type: integer
      updated_at:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
      used_memory:
        example: 8000000
        type: integer
    required:
    - created_at
    - id
    - level_name
    - system
    - timestamp
    - updated_at
    type: object
  schemas.PaginatedLogResponse:
    properties:
      items:
        description: ログの配列
        items:
          $ref: '#/definitions/schemas.LogResponse'
        type: array
      limit:
        description: 1ページあたりのアイテム数
        example: 10
        type: integer
      page:
        description: 現在のページ数
        example: 1
        type: integer
      total:
        description: 総アイテム数
        example: 100
        type: integer
      total_pages:
        description: 総ページ数
        example: 10
        type: integer
    type: object
  schemas.ResponseMessage:
    properties:
      message:
        type: string
    type: object
  schemas.Summary:
    properties:
      category:
        example: API Server
        type: string
      created_at:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
      data:
        items:
          $ref: '#/definitions/schemas.SummaryData'
        type: array
      id:
        example: 00000000-0000-0000-0000-000000000000
        type: string
      latest_log:
        $ref: '#/definitions/schemas.LogResponse'
      name:
        example: sample_system
        type: string
      updated_at:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
    required:
    - created_at
    - data
    - id
    - latest_log
    - updated_at
    type: object
  schemas.SummaryData:
    properties:
      base_time:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
      errorlog_count:
        example: 10
        type: integer
      infolog_count:
        example: 10
        type: integer
      warninglog_count:
        example: 10
        type: integer
    required:
    - base_time
    - errorlog_count
    - infolog_count
    - warninglog_count
    type: object
  schemas.SystemRequest:
    properties:
      category:
        example: API Server
        type: string
    type: object
  schemas.SystemResponse:
    properties:
      category:
        example: API Server
        type: string
      created_at:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
      id:
        example: 00000000-0000-0000-0000-000000000000
        type: string
      name:
        example: sample_system
        type: string
      updated_at:
        example: "2023-01-01T00:00:00.000000+09:00"
        type: string
    required:
    - created_at
    - id
    - updated_at
    type: object
  schemas.Traceback:
    properties:
      tb_filename:
        example: C:\User\USER\sample.py
        type: string
      tb_line:
        example: raise Exception("sample")
        type: string
      tb_lineno:
        example: 31
        type: integer
      tb_name:
        example: <module>
        type: string
    type: object
  schemas.TracebackResponse:
    properties:
      tb_filename:
        example: C:\User\USER\sample.py
        type: string
      tb_line:
        example: raise Exception("sample")
        type: string
      tb_lineno:
        example: 31
        type: integer
      tb_name:
        example: <module>
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: This is LogVista server.
  title: LogVista API
  version: 0.1.5
paths:
  /healthcheck:
    get:
      consumes:
      - application/json
      description: 200 OKが返ってくれば起動済み
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: ヘルスチェック用エンドポイント
      tags:
      - general
  /logs/:
    get:
      consumes:
      - application/json
      description: 蓄積されているログ情報を取得する。クエリパラメータでフィルタリングが可能。
      parameters:
      - default: 1
        description: 現在のページ
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 10
        description: 1ページあたりのアイテム数
        in: query
        minimum: 1
        name: pageSize
        type: integer
      - description: '検索する日付の開始範囲 (形式: YYYY-MM-DDTHH:MM:SSZ)'
        in: query
        name: startDate
        type: string
      - description: '検索する日付の終了範囲 (形式: YYYY-MM-DDTHH:MM:SSZ)'
        in: query
        name: endDate
        type: string
      - description: ログレベルでのフィルタ
        in: query
        name: levelName
        type: string
      - description: システム名でのフィルタ
        in: query
        name: systemName
        type: string
      - description: メッセージ内容の部分一致フィルタ
        in: query
        name: containMsg
        type: string
      - description: エラーの種類でのフィルタ
        in: query
        name: excType
        type: string
      - description: エラーの詳細でのキーワード部分一致フィルタ
        in: query
        name: excDetail
        type: string
      - description: ファイル名でのフィルタ
        in: query
        name: fileName
        type: string
      - description: エラーが発生した行番号でのフィルタ
        in: query
        name: lineno
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.PaginatedLogResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: 取得ログ情報
      tags:
      - logs
  /logs/python-logvista:
    post:
      consumes:
      - application/json
      description: json形式の配列で受け取ったログ情報を記録する
      parameters:
      - description: ログデータ
        in: body
        name: logs
        schema:
          items:
            $ref: '#/definitions/schemas.Log'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.LogResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: python-logvista用エンドポイント
      tags:
      - logs
  /masters/error-types:
    get:
      consumes:
      - application/json
      description: DB上に存在するエラー型名一覧を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: エラー型名一覧取得
      tags:
      - masters
  /masters/files:
    get:
      consumes:
      - application/json
      description: DB上に存在するファイル名一覧を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: ファイル名一覧取得
      tags:
      - masters
  /masters/levels:
    get:
      consumes:
      - application/json
      description: DB上に存在するログレベル一覧を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: ログレベル一覧取得
      tags:
      - masters
  /systems/:
    get:
      consumes:
      - application/json
      description: DB上に存在するシステム一覧を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.SystemResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: システム一覧取得
      tags:
      - systems
    put:
      consumes:
      - application/json
      description: DB上に存在するシステムを更新する
      parameters:
      - description: システムID
        in: query
        name: ID
        required: true
        type: string
      - description: Update System Request
        in: body
        name: system
        required: true
        schema:
          $ref: '#/definitions/schemas.SystemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: システム更新
      tags:
      - systems
  /systems/summary:
    get:
      consumes:
      - application/json
      description: DB上に存在するシステム別集計情報を取得する
      parameters:
      - description: システムID：指定しない場合は全てのシステムを取得
        in: query
        name: id
        type: string
      - default: 3600
        description: '集計時間スパン（秒）: 10秒刻みで指定可能'
        in: query
        minimum: 10
        name: timeSpan
        type: integer
      - default: 12
        description: 取得データ個数
        in: query
        minimum: 1
        name: dataCount
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.Summary'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: システム集計情報取得
      tags:
      - systems
swagger: "2.0"
